IMAGE_ubuntu_2204   = "bento/ubuntu-22.04"
IMAGE_Debian_12     = "bento/debian-12"

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeType1 = 1
  (1..NodeType1).each do |type1_id|
    config.vm.define "type1#{type1_id}" do |type1_vm|
      type1_vm.vm.box = IMAGE_ubuntu_2204
      type1_vm.vm.hostname = "type1#{type1_id}"
      type1_vm.vm.network "private_network", ip: "192.168.56.1#{type1_id}"
      type1_vm.vm.provider "virtualbox" do |v|
        v.name = "type1#{type1_id}"
        v.memory = 1024
        v.cpus = 1
      end
    end
  end
end
