# Packages List
packages:
    - vim
    # - vi
    # - nano
    - wget
    # - git
    # - ansible
    - net-tools
    - bash-completion
    # - ssh
    # - zsh
    # - unzip
    # - tar
    # - nginx
    # - apache